### ISSUE TITLE
Tutorial video pls?

### ISSUE THREAD

**Issue by MiClobiMC** [pop123123123/CLI_sentence_mixing#1]
Is a video tutorial possible?

**Comment by nbusser** [comment]
Hi, thank you for your report.
We actually planned to do such video tutorial. It should be uploaded before the end of the next week.

**Comment by MiClobiMC** [comment]
Thanks you

**Comment by nbusser** [comment]
Hi @MiClobiMC ,
Here is the [tutorial video](https://www.youtube.com/watch?v=JL6l4rNN3tU) you requested.
